server {
    server_name api-ykotika-45f4574d-8030-463f-95fc-30948e124a33.staging.infinite-ellipse.ru;
    root /var/www/ykotika/;

    location / {
        proxy_pass http://127.0.0.1:3010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}