# Используем официальный образ .NET SDK для сборки приложения (с .NET 8)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Устанавливаем рабочую директорию для сборки
WORKDIR /src

ARG LOGGING__LOGLEVEL__DEFAULT
ENV LOGGING__LOGLEVEL__DEFAULT=$LOGGING__LOGLEVEL__DEFAULT

ARG LOGGING__LOGLEVEL__MICROSOFT__ASPNETCORE
ENV LOGGING__LOGLEVEL__MICROSOFT__ASPNETCORE=$LOGGING__LOGLEVEL__MICROSOFT__ASPNETCORE

ARG ALLOWED_HOSTS
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS

ARG CONNECTIONSTRINGS__DBCONNECTION
ENV CONNECTIONSTRINGS__DBCONNECTION=$CONNECTIONSTRINGS__DBCONNECTION

ARG CONNECTIONSTRINGS__REDIS
ENV CONNECTIONSTRINGS__REDIS=$CONNECTIONSTRINGS__REDIS

ARG ACCESSTOKENOPTIONS__JWTOPTIONS__SECRETKEY
ENV ACCESSTOKENOPTIONS__JWTOPTIONS__SECRETKEY=$ACCESSTOKENOPTIONS__JWTOPTIONS__SECRETKEY

ARG ACCESSTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS
ENV ACCESSTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS=$ACCESSTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS

ARG REFRESHTOKENOPTIONS__JWTOPTIONS__SECRETKEY
ENV REFRESHTOKENOPTIONS__JWTOPTIONS__SECRETKEY=$REFRESHTOKENOPTIONS__JWTOPTIONS__SECRETKEY

ARG REFRESHTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS
ENV REFRESHTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS=$REFRESHTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS

ARG ENCRYPTIONOPTIONS__KEY
ENV ENCRYPTIONOPTIONS__KEY=$ENCRYPTIONOPTIONS__KEY

ARG ENCRYPTIONOPTIONS__AESIV
ENV ENCRYPTIONOPTIONS__AESIV=$ENCRYPTIONOPTIONS__AESIV

ARG EMAILVERIFIEROPTIONS__CREDENTIALS__ADDRESS
ENV EMAILVERIFIEROPTIONS__CREDENTIALS__ADDRESS=$EMAILVERIFIEROPTIONS__CREDENTIALS__ADDRESS

ARG EMAILVERIFIEROPTIONS__CREDENTIALS__PASSWORD
ENV EMAILVERIFIEROPTIONS__CREDENTIALS__PASSWORD=$EMAILVERIFIEROPTIONS__CREDENTIALS__PASSWORD

ARG EMAILVERIFIEROPTIONS__CREDENTIALS__PORT
ENV EMAILVERIFIEROPTIONS__CREDENTIALS__PORT=$EMAILVERIFIEROPTIONS__CREDENTIALS__PORT

ARG EMAILVERIFIEROPTIONS__CREDENTIALS__ENABLESSL
ENV EMAILVERIFIEROPTIONS__CREDENTIALS__ENABLESSL=$EMAILVERIFIEROPTIONS__CREDENTIALS__ENABLESSL

ARG EMAILVERIFIEROPTIONS__CREDENTIALS__HOST
ENV EMAILVERIFIEROPTIONS__CREDENTIALS__HOST=$EMAILVERIFIEROPTIONS__CREDENTIALS__HOST

ARG ALLOWED_ORIGINS
ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS
# Копируем всю директорию с исходным кодом в контейнер
COPY src/ ./
# Очищаем проект перед сборкой
RUN dotnet clean Ykotika.sln

# Сборка проекта
RUN dotnet build Ykotika.sln -c Debug

# Публикуем проект
RUN dotnet publish Ykotika.WebAPI/Ykotika.WebAPI.csproj -c Debug -o /app

# Используем официальный образ .NET Runtime для запуска приложения (с .NET 8)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Устанавливаем рабочую директорию для исполнимого файла
WORKDIR /app

# Копируем собранное приложение из стадии сборки
COPY --from=build /app ./

# Открываем порт для приложения
EXPOSE 8080
EXPOSE 8081

# Указываем команду для запуска веб-приложения
ENTRYPOINT ["dotnet", "Ykotika.WebAPI.dll"]
