# Используем официальный образ .NET SDK для сборки приложения (с .NET 8)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Устанавливаем рабочую директорию для сборки
WORKDIR /src

# Копируем всю директорию с исходным кодом в контейнер
COPY src/ ./
# Очищаем проект перед сборкой
RUN dotnet clean Ykotika.sln

# Сборка проекта
RUN dotnet build Ykotika.sln -c Debug

# Публикуем проект
RUN dotnet publish Ykotika.WebAPI/Ykotika.WebAPI.csproj -c Debug -o /app

# Используем официальный образ .NET Runtime для запуска приложения (с .NET 8)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Устанавливаем рабочую директорию для исполнимого файла
WORKDIR /app

ARG LOGGING__LOG_LEVEL__DEFAULT
ENV LOGGING__LOG_LEVEL__DEFAULT=$LOGGING__LOG_LEVEL__DEFAULT

ARG LOGGING__LOG_LEVEL__MICROSOFT__ASP_NET_CORE
ENV LOGGING__LOG_LEVEL__MICROSOFT__ASP_NET_CORE=$LOGGING__LOG_LEVEL__MICROSOFT__ASP_NET_CORE

ARG ALLOWED_HOSTS
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS

ARG CONNECTION_STRINGS__DB_CONNECTION
ENV CONNECTION_STRINGS__DB_CONNECTION=$CONNECTION_STRINGS__DB_CONNECTION

ARG CONNECTION_STRINGS__REDIS
ENV CONNECTION_STRINGS__REDIS=$CONNECTION_STRINGS__REDIS

ARG ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY
ENV ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY=$ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY

ARG ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS
ENV ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS=$ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS

ARG REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY
ENV REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY=$REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY

ARG REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS
ENV REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS=$REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS

ARG ENCRYPTION_OPTIONS__KEY
ENV ENCRYPTION_OPTIONS__KEY=$ENCRYPTION_OPTIONS__KEY

ARG ENCRYPTION_OPTIONS__AES_IV
ENV ENCRYPTION_OPTIONS__AES_IV=$ENCRYPTION_OPTIONS__AES_IV

ARG EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ADDRESS
ENV EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ADDRESS=$EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ADDRESS

ARG EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PASSWORD
ENV EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PASSWORD=$EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PASSWORD

ARG EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PORT
ENV EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PORT=$EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PORT

ARG EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ENABLE_SSL
ENV EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ENABLE_SSL=$EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ENABLE_SSL

ARG EMAIL_VERIFIER_OPTIONS__CREDENTIALS__HOST
ENV EMAIL_VERIFIER_OPTIONS__CREDENTIALS__HOST=$EMAIL_VERIFIER_OPTIONS__CREDENTIALS__HOST

ARG ALLOWED_ORIGINS
ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS

# Копируем собранное приложение из стадии сборки
COPY --from=build /app ./

# Открываем порт для приложения
EXPOSE 8080
EXPOSE 8081

# Указываем команду для запуска веб-приложения
ENTRYPOINT ["dotnet", "Ykotika.WebAPI.dll"]
