// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ykotika.Persistence;

#nullable disable

namespace Ykotika.Persistence.Migrations
{
    [DbContext(typeof(YkotikaDbContext))]
    [Migration("20241228174308_ChangedProduct")]
    partial class ChangedProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutsourceShopProduct", b =>
                {
                    b.Property<Guid>("OutsourceShopsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("OutsourceShopsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OutsourceShopProduct");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Entities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormInputs");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.InputRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormInputId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmittedFormDataId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormInputId");

                    b.HasIndex("SubmittedFormDataId");

                    b.ToTable("FormInputRecords");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Agreement", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("OfferId");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Author", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Category", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ImageId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Director", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.File", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("ProductId");

                    b.HasIndex("Name", "RelativePath")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.FormRecord", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("FormId");

                    b.ToTable("FormRecords");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Moderator", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.OutsourceShop", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LogoId");

                    b.ToTable("OutsourceShops");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Product", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FormRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasIndex("FormRecordId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("FormId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.User", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<bool>("ConfirmedPolicy")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("PictureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PictureId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OutsourceShopProduct", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.OutsourceShop", null)
                        .WithMany()
                        .HasForeignKey("OutsourceShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Entity", b =>
                {
                    b.OwnsOne("Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Entities");

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Input", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Form", "Form")
                        .WithMany("Inputs")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.InputRecord", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Input", "FormInput")
                        .WithMany("SubmittedFormFieldsData")
                        .HasForeignKey("FormInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.FormRecord", "SubmittedFormData")
                        .WithMany("InputRecords")
                        .HasForeignKey("SubmittedFormDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormInput");

                    b.Navigation("SubmittedFormData");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Agreement", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Author", "Author")
                        .WithMany("Agreements")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Agreement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Offer", "Offer")
                        .WithMany("Agreements")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Author", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Author", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ykotika.Domain.ValueObjects.AuthorRequest", "Request", b1 =>
                        {
                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TellAboutYourself")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WhichSocial")
                                .HasColumnType("integer");

                            b1.HasKey("AuthorId");

                            b1.ToTable("Authors");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");

                            b1.OwnsOne("Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b2 =>
                                {
                                    b2.Property<Guid>("AuthorRequestAuthorId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("AuthorRequestAuthorId");

                                    b2.ToTable("Authors");

                                    b2.WithOwner()
                                        .HasForeignKey("AuthorRequestAuthorId");
                                });

                            b1.Navigation("Timestamps")
                                .IsRequired();
                        });

                    b.OwnsMany("Ykotika.Domain.ValueObjects.Social", "Socials", b1 =>
                        {
                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AuthorId", "Id");

                            b1.ToTable("Social");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");
                        });

                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("Socials");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Category", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Director", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Director", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.File", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.File", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Form", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.FormRecord", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Form", "Form")
                        .WithMany("FormRecords")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.FormRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Moderator", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Moderator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Offer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.OutsourceShop", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.OutsourceShop", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.FormRecord", "FormRecord")
                        .WithMany()
                        .HasForeignKey("FormRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRecord");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.ProductType", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.User", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Input", b =>
                {
                    b.Navigation("SubmittedFormFieldsData");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Author", b =>
                {
                    b.Navigation("Agreements");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.Navigation("FormRecords");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.FormRecord", b =>
                {
                    b.Navigation("InputRecords");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Agreements");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
