// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ykotika.Persistence;

#nullable disable

namespace Ykotika.Persistence.Migrations
{
    [DbContext(typeof(YkotikaDbContext))]
    partial class YkotikaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct", (string)null);
                });

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("ChatUser", (string)null);
                });

            modelBuilder.Entity("FileMessage", b =>
                {
                    b.Property<string>("AttachmentsPath")
                        .HasColumnType("text");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("AttachmentsPath", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("FileMessage", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Entities", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.File", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Path");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Agreement", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("OfferId");

                    b.HasIndex("UserId");

                    b.ToTable("Agreements", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Category", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("ImagePath");

                    b.HasIndex("UserId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Chat", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Director", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Directors", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.FormRecord", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("FormRecords", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Message", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Moderator", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Moderators", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.OutsourceShop", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ImagePath");

                    b.ToTable("OutsourceShops", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Product", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcePath")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("FormRecordId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SourcePath");

                    b.HasIndex("UserId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<List<string>>("ArticlePattern")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("ManualLink")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductTypes", (string)null);
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.User", b =>
                {
                    b.HasBaseType("Ykotika.Domain.Entities.Entity");

                    b.Property<bool>("ConfirmedPersonalDataProcessingPolicy")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ImagePath");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatUser", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Chat", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileMessage", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("AttachmentsPath")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Author", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Author", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Ykotika.Domain.Entities.Author.Request#Ykotika.Domain.ValueObjects.AuthorRequest", "Request", b1 =>
                        {
                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TellAboutYourself")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("WhichSocial")
                                .HasColumnType("integer");

                            b1.HasKey("AuthorUserId");

                            b1.ToTable("Authors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuthorUserId");

                            b1.OwnsOne("Ykotika.Domain.Entities.Author.Request#Ykotika.Domain.ValueObjects.AuthorRequest.Timestamps#Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b2 =>
                                {
                                    b2.Property<Guid>("AuthorRequestAuthorUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("AuthorRequestAuthorUserId");

                                    b2.ToTable("Authors", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AuthorRequestAuthorUserId");
                                });

                            b1.Navigation("Timestamps")
                                .IsRequired();
                        });

                    b.OwnsMany("Ykotika.Domain.Entities.Author.Socials#Ykotika.Domain.ValueObjects.Social", "Socials", b1 =>
                        {
                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AuthorUserId", "Id");

                            b1.ToTable("Social", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuthorUserId");
                        });

                    b.OwnsOne("Ykotika.Domain.Entities.Author.Timestamps#Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("AuthorUserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("AuthorUserId");

                            b1.ToTable("Authors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AuthorUserId");
                        });

                    b.Navigation("Request")
                        .IsRequired();

                    b.Navigation("Socials");

                    b.Navigation("Timestamps")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Entity", b =>
                {
                    b.OwnsOne("Ykotika.Domain.Entities.Entity.Timestamps#Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("EntityId");

                            b1.ToTable("Entities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EntityId");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.File", b =>
                {
                    b.OwnsOne("Ykotika.Domain.Entities.File.Timestamps#Ykotika.Domain.ValueObjects.Timestamps", "Timestamps", b1 =>
                        {
                            b1.Property<string>("FilePath")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("FilePath");

                            b1.ToTable("Files", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FilePath");
                        });

                    b.Navigation("Timestamps")
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Agreement", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Agreement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Offer", "Offer")
                        .WithMany("Agreements")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany("Agreements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Category", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Image")
                        .WithMany()
                        .HasForeignKey("ImagePath")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Chat", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Chat", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Director", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Director", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Form", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ykotika.Domain.Entities.Form.Inputs#Ykotika.Domain.Entities.Form+Input", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("FormId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("FormId", "Id");

                            b1.ToTable("Input", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FormId");

                            b1.OwnsOne("Ykotika.Domain.Entities.Form.Inputs#Ykotika.Domain.Entities.Form+Input.ExtraAttributes#Ykotika.Domain.Entities.Form+InputExtraAttributes", "ExtraAttributes", b2 =>
                                {
                                    b2.Property<Guid>("InputFormId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("InputId")
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsRequired")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false);

                                    b2.Property<string>("Label")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int?>("MaxSelections")
                                        .HasColumnType("integer");

                                    b2.Property<string[]>("Options")
                                        .HasColumnType("text[]");

                                    b2.Property<string>("Placeholder")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Regex")
                                        .HasColumnType("text");

                                    b2.HasKey("InputFormId", "InputId");

                                    b2.ToTable("Input", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("InputFormId", "InputId");
                                });

                            b1.Navigation("ExtraAttributes")
                                .IsRequired();
                        });

                    b.Navigation("Inputs");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.FormRecord", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Form", "Form")
                        .WithMany("FormRecords")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.FormRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ykotika.Domain.Entities.FormRecord.InputRecords#Ykotika.Domain.Entities.FormRecord+InputRecord", "InputRecords", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<Guid>("FormRecordId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id", "FormRecordId");

                            b1.HasIndex("FormRecordId");

                            b1.ToTable("InputRecord", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FormRecordId");
                        });

                    b.Navigation("Form");

                    b.Navigation("InputRecords");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Message", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Message", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Moderator", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Moderator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Offer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.OutsourceShop", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.OutsourceShop", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Image")
                        .WithMany()
                        .HasForeignKey("ImagePath")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Chat", "Discussion")
                        .WithMany()
                        .HasForeignKey("DiscussionId");

                    b.HasOne("Ykotika.Domain.Entities.FormRecord", "FormRecord")
                        .WithMany()
                        .HasForeignKey("FormRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Source")
                        .WithMany()
                        .HasForeignKey("SourcePath")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Ykotika.Domain.Entities.Product.Comments#Ykotika.Domain.ValueObjects.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductId", "Id");

                            b1.HasIndex("AuthorId");

                            b1.ToTable("Comment", (string)null);

                            b1.HasOne("Ykotika.Domain.Entities.User", "Author")
                                .WithMany()
                                .HasForeignKey("AuthorId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.Navigation("Author");
                        });

                    b.OwnsMany("Ykotika.Domain.Entities.Product.Images#Ykotika.Domain.ValueObjects.ImageListItem", "Images", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ImagePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("integer");

                            b1.HasKey("ProductId", "Id");

                            b1.HasIndex("ImagePath");

                            b1.ToTable("ImageListItem", (string)null);

                            b1.HasOne("Ykotika.Domain.Entities.File", "Image")
                                .WithMany()
                                .HasForeignKey("ImagePath")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.Navigation("Image");
                        });

                    b.OwnsMany("Ykotika.Domain.Entities.Product.OutsourceShops#Ykotika.Domain.ValueObjects.OutsourceShopProductInfo", "OutsourceShops", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("OutsourceShopId")
                                .HasColumnType("uuid");

                            b1.HasKey("ProductId", "Id");

                            b1.HasIndex("OutsourceShopId");

                            b1.ToTable("OutsourceShopProductInfo", (string)null);

                            b1.HasOne("Ykotika.Domain.Entities.OutsourceShop", "OutsourceShop")
                                .WithMany()
                                .HasForeignKey("OutsourceShopId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.Navigation("OutsourceShop");
                        });

                    b.OwnsMany("Ykotika.Domain.Entities.Product.Tags#Ykotika.Domain.ValueObjects.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("Tag", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Comments");

                    b.Navigation("Discussion");

                    b.Navigation("FormRecord");

                    b.Navigation("Images");

                    b.Navigation("OutsourceShops");

                    b.Navigation("ProductType");

                    b.Navigation("Source");

                    b.Navigation("Tags");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.ProductType", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.User", b =>
                {
                    b.HasOne("Ykotika.Domain.Entities.Entity", null)
                        .WithOne()
                        .HasForeignKey("Ykotika.Domain.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ykotika.Domain.Entities.File", "Image")
                        .WithMany()
                        .HasForeignKey("ImagePath")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Form", b =>
                {
                    b.Navigation("FormRecords");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Agreements");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ykotika.Domain.Entities.User", b =>
                {
                    b.Navigation("Agreements");
                });
#pragma warning restore 612, 618
        }
    }
}
