name: Development Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}  # Переменная для IP-адреса из секретов

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to server
        env:  # Передача SERVER_IP в эту команду
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@$SERVER_IP "
            cd /var/www/ykotika/dev/ykotika.ru-backend/ && 
            sudo git fetch --all && 
            sudo git pull origin dev && 
            cd .. && 
            sudo docker-compose down api && 
            sudo docker-compose up -d --build api"
