name: Staging building and deployment
description: HAS specific steps! | Used for building stage image, pushing it to registry and deploy it on dev server

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor
        run: |
          echo '${{ secrets.HARBOR_PUBLISHER_TOKEN }}' | \
          docker login ${{ vars.HARBOR_URL }} \
          -u '${{ secrets.HARBOR_ROBOT_PUBLISHER_NAME }}' \
          --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ vars.HARBOR_URL }}/${{ vars.HARBOR_PROJECT_NAME }}/${{ vars.HARBOR_REPO_NAME }}:staging
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            LOGGING__LOG_LEVEL__DEFAULT=${{ vars.LOGGING__LOGLEVEL__DEFAULT }}
            LOGGING__LOG_LEVEL__MICROSOFT__ASP_NET_CORE=${{ vars.LOGGING__LOGLEVEL__MICROSOFT__ASPNETCORE }}
            ALLOWED_HOSTS=${{ vars.ALLOWEDHOSTS }}
            CONNECTION_STRINGS__DB_CONNECTION=${{ secrets.CONNECTIONSTRINGS__DBCONNECTION }}
            CONNECTION_STRINGS__REDIS=${{ secrets.CONNECTIONSTRINGS__REDIS }}
            ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY=${{ secrets.ACCESSTOKENOPTIONS__JWTOPTIONS__SECRETKEY }}
            ACCESS_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS=${{ vars.ACCESSTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS }}
            REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__SECRET_KEY=${{ secrets.REFRESHTOKENOPTIONS__JWTOPTIONS__SECRETKEY }}
            REFRESH_TOKEN_OPTIONS__JWT_OPTIONS__EXPIRES_HOURS=${{ vars.REFRESHTOKENOPTIONS__JWTOPTIONS__EXPIRESHOURS }}
            ENCRYPTION_OPTIONS__KEY=${{ secrets.ENCRYPTIONOPTIONS__KEY }}
            ENCRYPTION_OPTIONS__AES_IV=${{ secrets.ENCRYPTIONOPTIONS__AESIV }}
            EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ADDRESS=${{ vars.EMAILVERIFIEROPTIONS__CREDENTIALS__ADDRESS }}
            EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PASSWORD=${{ secrets.EMAILVERIFIEROPTIONS__CREDENTIALS__PASSWORD }}
            EMAIL_VERIFIER_OPTIONS__CREDENTIALS__PORT=${{ vars.EMAILVERIFIEROPTIONS__CREDENTIALS__PORT }}
            EMAIL_VERIFIER_OPTIONS__CREDENTIALS__ENABLE_SSL=${{ vars.EMAILVERIFIEROPTIONS__CREDENTIALS__ENABLESSL }}
            EMAIL_VERIFIER_OPTIONS__CREDENTIALS__HOST=${{ vars.EMAILVERIFIEROPTIONS__CREDENTIALS__HOST }}
            ALLOWED_ORIGINS=${{ vars.ALLOWEDORIGINS }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Deploy to staging server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_SERVER_USER }}@${{ vars.DEV_SERVER_IP }} bash <<'EOF'
            export DOCKER_CONFIG="$HOME/.docker"
            mkdir -p "$DOCKER_CONFIG"
            echo -n '${{ secrets.HARBOR_PULLER_TOKEN }}' | docker login ${{ vars.HARBOR_URL }} -u '${{ secrets.HARBOR_ROBOT_PULLER_NAME }}' --password-stdin
            cd ${{ vars.DCY_ABS_PATH }}
            docker compose pull
            docker compose up -d
            docker logout ${{ vars.HARBOR_URL }}
            rm -rf "$DOCKER_CONFIG"
          EOF