name: Testing

on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      
jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Running tests
        run: |
          chmod +x ./run_test.sh  
          ./run_test.sh